apiVersion: v1
kind: Service
metadata:
  name: linked-data-service
  namespace: web
  labels:
    app: linked-data-service
    component: api
spec:
  type: ClusterIP
  selector:
    app: linked-data-service
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    protocol: TCP
  sessionAffinity: None
