apiVersion: v1
kind: Service
metadata:
  name: linked-data-service
  labels:
    app: linked-data-service
spec:
  type: ClusterIP
  selector:
    app: linked-data-service
  ports:
    - name: http
      port: 3000
      targetPort: 3000
